// AUTO-GENERATED by scripts/apply-app-identity.js — DO NOT EDIT.
// Edit app.identity.json instead, then run: npm run identity

export type AppEnvironment = 'dev' | 'staging' | 'prod';

export const BASE_APP_ID = 'com.mobileappbase' as const;
export const PROJECT_NAME = 'MobileAppBase' as const;

export const APP_IDENTITY: Record<
  AppEnvironment,
  { appId: string; displayName: string }
> = {
  dev: {
    appId: 'com.mobileappbase.dev',
    displayName: 'AppBase Dev',
  },
  staging: {
    appId: 'com.mobileappbase.staging',
    displayName: 'AppBase Stg',
  },
  prod: {
    appId: 'com.mobileappbase',
    displayName: 'AppBase',
  },
};
