#!/bin/bash
#
# One-command setup for a fresh clone.
#
#   ./scripts/bootstrap.sh
#
# Idempotent — safe to re-run after pulling changes or upgrading React Native.
#
set -euo pipefail

cd "$(dirname "$0")/.."

# CocoaPods normalizes paths as UTF-8 and crashes with
# "Unicode Normalization not appropriate for ASCII-8BIT" when the shell has no
# UTF-8 locale — which happens on any repo path containing spaces.
export LANG="${LANG:-en_US.UTF-8}"
export LC_ALL="${LC_ALL:-en_US.UTF-8}"

info()  { printf '\033[0;34m▸\033[0m %s\n' "$1"; }
ok()    { printf '\033[0;32m✓\033[0m %s\n' "$1"; }
warn()  { printf '\033[0;33m!\033[0m %s\n' "$1"; }
fail()  { printf '\033[0;31m✗\033[0m %s\n' "$1" >&2; exit 1; }

# ─────────────────────────────────────────────────────── prerequisites ─────
info 'Checking prerequisites'

command -v node >/dev/null || fail 'Node is not installed. Install Node >= 22.11 (see .nvmrc).'

NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
NODE_MINOR=$(node -p 'process.versions.node.split(".")[1]')
if [ "$NODE_MAJOR" -lt 22 ] || { [ "$NODE_MAJOR" -eq 22 ] && [ "$NODE_MINOR" -lt 11 ]; }; then
  fail "Node $(node -v) is too old — React Native 0.86 needs >= 22.11. Run: nvm use"
fi
ok "Node $(node -v)"

if command -v java >/dev/null; then
  ok "Java $(java -version 2>&1 | head -1 | cut -d'"' -f2)"
else
  warn 'Java not found — Android builds need JDK 17.'
fi

# ─────────────────────────────────────────────────────────── JS deps ───────
info 'Installing npm dependencies'
npm install
ok 'npm dependencies installed (postinstall regenerated the identity files)'

# ──────────────────────────────────────────────────────────── Android ──────
if [ ! -f android/local.properties ]; then
  SDK_DIR="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}"
  if [ -d "$SDK_DIR" ]; then
    printf '## Auto-generated by scripts/bootstrap.sh — machine-specific, git-ignored.\nsdk.dir=%s\n' "$SDK_DIR" > android/local.properties
    ok "android/local.properties → $SDK_DIR"
  else
    warn "Android SDK not found. Set ANDROID_HOME or create android/local.properties manually."
  fi
else
  ok 'android/local.properties already present'
fi

# ─────────────────────────────────────────────────── default .env copy ─────
if [ ! -f .env ]; then
  cp .env.dev .env
  ok '.env created from .env.dev (default for bare gradle/xcodebuild invocations)'
fi

# ──────────────────────────────────────────────────────────────── iOS ──────
if [ "$(uname)" = "Darwin" ]; then
  info 'Installing Ruby gems'
  bundle install
  ok 'gems installed'

  info 'Configuring Xcode build configurations and schemes'
  bundle exec ruby scripts/ios-setup-flavors.rb

  info 'Installing pods (this takes a few minutes on a cold cache)'
  bundle exec pod install --project-directory=ios
  ok 'pods installed'
else
  warn 'Not macOS — skipping iOS setup.'
fi

# ───────────────────────────────────────────────────────────── verify ──────
info 'Verifying the toolchain'
npm run typecheck
ok 'typecheck passed'

cat <<'EOF'

  Setup complete.

    npm run ios:dev         npm run android:dev
    npm run ios:staging     npm run android:staging
    npm run ios:prod        npm run android:prod

    npm run validate        typecheck + lint + test

  Any email and an 8+ character password will sign you in (the API is mocked).

  Next: read README.md → "Starting a NEW project from this template".

EOF
